config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get 'oauth2_callbacks', to: 'oauth2_callbacks#create'

  put :sheets, to: 'sheets#update'

  root to: 'sheets#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/candidate.rb
class Candidate < ApplicationRecord
  validates :email, presence: true
  validates :row, presence: true, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/concerns/google_sheets_credentials.rb
module GoogleSheetsCredentials
  extend ActiveSupport::Concern

  def user_api_credentials
    @user_api_credentials ||= GoogleSheets::UserCredentials.new(
      current_user.id, request: request,
                       callback_url: oauth2_callbacks_url
    )
  end

  def authorize_google_sheets_api!
    return if user_api_credentials.authorized?

    redirect_to user_api_credentials.autorization_url(root_url)
  end
end

app/controllers/oauth2_callbacks_controller.rb
require 'googleauth'
require 'googleauth/web_user_authorizer'

class Oauth2CallbacksController < ApplicationController
  include GoogleSheetsCredentials

  def create
    target_url = user_api_credentials.handle_auth_callback

    redirect_to target_url
  end
end

app/controllers/sheets_controller.rb
class SheetsController < ApplicationController
  include GoogleSheetsCredentials

  before_action :authorize_google_sheets_api!

  def index; end

  def update
    processor.call
    if processor.new_records_count.positive?
      flash[:notice] = "#{view_context.pluralize(processor.new_records_count, 'new candidate')} processed"
    else
      flash[:notice] = 'I am Sorry! No new candidates!'
    end
  rescue SpreadsheetProcessor::ReadError
    flash[:error] = "An error ocurred trying to read the Spreadsheet"
  ensure
    redirect_to root_path
  end

  private

  def processor
    @processor ||= SpreadsheetProcessor.new(user_api_credentials.credentials)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TalkpushTest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |key, value| %>
      <%= content_tag :div, value, class: "flash #{key}" %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/sheets/index.html.erb
<h1>Google Sheets Test</h1>
<%= form_tag sheets_path, method: :put do %>
<button>Check for new responses</button>
<% end %>